# Generated by Django 2.2 on 2019-04-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20190415_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.IntegerField(choices=[(0, '初级'), (1, '中级'), (2, '高级')], default=0, verbose_name='课程等级'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.IntegerField(choices=[(0, 'JAVA'), (1, 'PYTHON'), (2, 'C'), (3, 'C++')], default=1, verbose_name='课程类型'),
        ),
    ]
