# Generated by Django 2.2 on 2019-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20190415_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='', upload_to='TeacherPhoto/%Y/%m/%d', verbose_name='讲师照片'),
        ),
    ]
