# Generated by Django 2.2 on 2019-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosource',
            name='time',
            field=models.CharField(default='1', max_length=10, verbose_name='视频长度'),
        ),
    ]
