# Generated by Django 2.2 on 2019-04-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_videosource_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videosource',
            name='time',
        ),
    ]
