# Generated by Django 2.2 on 2019-04-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerfiy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱地址')),
                ('type', models.CharField(choices=[(0, 'register'), (1, 'forget')], default=0, max_length=2, verbose_name='邮件类型')),
                ('send_time', models.DateTimeField(auto_now=True, verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '邮箱验证',
                'verbose_name_plural': '邮箱验证',
            },
        ),
    ]
