# Generated by Django 2.2 on 2019-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverfiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverfiy',
            name='type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], default='注册', max_length=10, verbose_name='邮件类型'),
        ),
    ]
